# Generated by Django 5.2.14 on 2026-06-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_post', 'New Post'), ('new_event', 'New Event'), ('event_reminder', 'Event Reminder'), ('rsvp', 'RSVP'), ('member_join', 'Member Join')], max_length=32),
        ),
    ]
