# Generated by Django 5.2.14 on 2026-05-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_add_channel_type_and_post_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_type',
            field=models.CharField(choices=[('general', 'General'), ('announcements', 'Announcements'), ('events', 'Events'), ('media', 'Media'), ('help', 'Help')], default='general', max_length=20),
        ),
    ]
