# Generated by Django 5.2.14 on 2026-05-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_add_channel_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
