# Generated by Django 5.2.14 on 2026-05-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0006_community_add_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='cover_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
