# Generated by Django 5.2.14 on 2026-05-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0006_community_add_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_type',
            field=models.CharField(choices=[('general', 'General'), ('announcements', 'Announcements'), ('events', 'Events'), ('resources', 'Resources'), ('help', 'Help')], default='general', max_length=20),
        ),
    ]
