# Generated by Django 5.2.14 on 2026-05-29 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0007_alter_channel_type_replace_media_with_resources'),
        ('communities', '0007_alter_community_cover_image_url'),
    ]

    operations = [
    ]
