# Generated by Django 5.2.14 on 2026-05-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rsvp_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cover_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
