# Generated by Django 5.2.14 on 2026-05-29 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_cover_image_url'),
        ('events', '0003_rsvp_status_maybe_to_interested'),
    ]

    operations = [
    ]
